version: "3"

services:
  panic:
    build:
      context: .
      dockerfile: development/Dockerfile
    env_file:
      - development.env
    volumes:
      - ${HOME}/.ssh:/home/user/.ssh
      - ${HOME}/.gitconfig:/home/user/.gitconfig
      - ${HOME}/.gitconfig_global:/home/user/.gitconfig_global
      - ./:/app
    command: >
      ./panic/container_boot.sh
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - development.env

volumes:
  postgres_data:
