version: "3"

services:
  panic:
    build:
      context: .
      dockerfile: development/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ${HOME}/.ssh:/home/user/.ssh
      - ${HOME}/.gitconfig:/home/user/.gitconfig
      - ${HOME}/.gitconfig_global:/home/user/.gitconfig_global
      - ./:/app
    command: >
      ./panic/container_boot.sh
    env_file:
      - ./environments/local.env
  db:
    image: postgres:12.0-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./environments/local.env

volumes:
  postgres_data:
