[tool.poetry]
name = "panic"
version = "0.1.0"
description = "Grocery Shopping App"
authors = ["Niall Byrne <niall@niallbyrne.ca>"]
license = "MPL-2"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.2.4"
djangorestframework = "^3.12.0"
djangorestframework-simplejwt = ">=4.7.1,<4.8.0"
django-filter = "^2.4.0"
django-bleach = "^0.7.2"
django-cors-headers = "^3.9.0"
django-split-settings = "^1.0.1"
django-timezone-field = "^4.1.1"
django-watchman = "^1.2.0"
dj-rest-auth = {extras = ["with_social"], version = "^1.0.0"}
drf-yasg = "^1.20.0"
langcodes = "^3.1.0"
pendulum = "2.1.2"
psycopg2 = "^2.8.4"
pytz = "^2021.1"
gevent = "^21.8.0"
gunicorn = "^20.1.0"
sphinxcontrib-django = {version = "^0.5.1", optional = true}
Sphinx = {version = "^4.0.2", optional = true}

[tool.poetry.extras]
docs = ["Sphinx", "sphinxcontrib-django"]

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
commitizen = "^2.17.8"
debugpy = "^1.3.0"
isort = "^5.8.0"
Faker = "^8.11.0"
freezegun = "^1.1.0"
mypy = "^0.910"
pydocstyle = "^6.1.1"
pylint = "^2.8.3"
pylint-django = "^2.4.4"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-django = "^4.4.0"
pytest-pylint = "^0.18.0"
pytest-subtests = "^0.5.0"
parameterized = "^0.8.1"
safety = "^1.10.3"
types-freezegun = "^1.1.0"
types-pytz = "^2021.1.0"
yapf = "^0.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
