# Generated by Django 3.0.11 on 2021-02-04 14:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0001_initial'),
  ]

  operations = [
      migrations.AlterModelManagers(
          name='transaction',
          managers=[
              ('consumption', django.db.models.manager.Manager()),
          ],
      ),
  ]
