# Generated by Django 3.0.12 on 2021-02-05 20:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0001_initial'),
  ]

  operations = [
      migrations.AlterModelManagers(
          name='transaction',
          managers=[
              ('consumption', django.db.models.manager.Manager()),
          ],
      ),
      migrations.RemoveField(
          model_name='transaction',
          name='user',
      ),
  ]
