# Generated by Django 3.0.12 on 2021-02-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0004_inventory_20210206_2131'),
  ]

  operations = [
      migrations.AlterModelManagers(
          name='transaction',
          managers=[],
      ),
  ]
