# Generated by Django 3.0.12 on 2021-02-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0005_transaction_20210217_2100'),
  ]

  operations = [
      migrations.RenameField(
          model_name='item',
          old_name='expired',
          new_name='_expired',
      ),
      migrations.RemoveField(
          model_name='item',
          name='next_expiry_date',
      ),
      migrations.RenameField(
          model_name='item',
          old_name='next_expiry_quantity',
          new_name='_next_expiry_quantity',
      ),
  ]
