# Generated by Django 3.0.13 on 2021-02-24 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0006_item_properties_20210221_1906'),
  ]

  operations = [
      migrations.AlterField(
          model_name='item',
          name='_expired',
          field=models.FloatField(
              blank=True,
              default=None,
              null=True,
              validators=[
                  django.core.validators.MinValueValidator(0),
                  django.core.validators.MaxValueValidator(10000)
              ]
          ),
      ),
      migrations.AlterField(
          model_name='item',
          name='_next_expiry_quantity',
          field=models.FloatField(
              blank=True,
              default=None,
              null=True,
              validators=[
                  django.core.validators.MinValueValidator(0),
                  django.core.validators.MaxValueValidator(10000)
              ]
          ),
      ),
  ]
