# Generated by Django 3.0.13 on 2021-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0007_item_cache_properties_20210224_1927'),
  ]

  operations = [
      migrations.RemoveConstraint(
          model_name='item',
          name='item per user',
      ),
      migrations.RemoveConstraint(
          model_name='shelf',
          name='shelf per user',
      ),
      migrations.RemoveConstraint(
          model_name='store',
          name='store per user',
      ),
      migrations.RemoveIndex(
          model_name='item',
          name='kitchen_ite_index_51a552_idx',
      ),
      migrations.RemoveIndex(
          model_name='shelf',
          name='kitchen_she_index_ff871c_idx',
      ),
      migrations.RemoveIndex(
          model_name='store',
          name='kitchen_sto_index_3262d6_idx',
      ),
      migrations.RenameField(
          model_name='item',
          old_name='index',
          new_name='_index',
      ),
      migrations.RenameField(
          model_name='shelf',
          old_name='index',
          new_name='_index',
      ),
      migrations.RenameField(
          model_name='store',
          old_name='index',
          new_name='_index',
      ),
      migrations.AddIndex(
          model_name='item',
          index=models.Index(
              fields=['_index'], name='kitchen_ite__index_5aa506_idx'
          ),
      ),
      migrations.AddIndex(
          model_name='shelf',
          index=models.Index(
              fields=['_index'], name='kitchen_she__index_3f6040_idx'
          ),
      ),
      migrations.AddIndex(
          model_name='store',
          index=models.Index(
              fields=['_index'], name='kitchen_sto__index_af8b16_idx'
          ),
      ),
  ]
