# Generated by Django 3.2.3 on 2021-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0009_preferred_stores_cascades_20210309_1949'),
  ]

  operations = [
      migrations.AlterField(
          model_name='inventory',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
      migrations.AlterField(
          model_name='item',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
      migrations.AlterField(
          model_name='preferredstore',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
      migrations.AlterField(
          model_name='shelf',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
      migrations.AlterField(
          model_name='store',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
      migrations.AlterField(
          model_name='suggesteditem',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
      migrations.AlterField(
          model_name='transaction',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
  ]
