# Generated by Django 3.2.6 on 2021-09-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
      ('kitchen', '0010_bigauto_field_20210609_0150'),
  ]

  operations = [
      migrations.AlterField(
          model_name='item',
          name='shelf',
          field=models.ForeignKey(
              blank=True,
              null=True,
              on_delete=django.db.models.deletion.SET_NULL,
              to='kitchen.shelf'
          ),
      ),
  ]
