"""Django settings for panic project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from split_settings.tools import include

from . import BASE_DIR
from .settings_database import DATABASES_AVAILABLE
from .settings_restframework import REST_FRAMEWORK_AVAILABLE

BASE_SETTINGS = [
    'settings_apps.py',
    'settings_email.py',
    'settings_jwt.py',
    'settings_registration.py',
]

include(*BASE_SETTINGS)

# Environment Configuration

ENVIRONMENT = os.environ.get('DJANGO_ENVIRONMENT', 'local')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'dj_rest_auth',
    'corsheaders',
    'timezone_field',
    'user',
    'appengine',
    'kitchen',
    'drf_yasg',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'spa_security',
    'social_accounts',
    'django_bleach',
    'utilities',
    'watchman',
    'legal',
    'naturalsortfield',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ROOT_URLCONF = 'root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {'default': DATABASES_AVAILABLE[ENVIRONMENT]}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model
# https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-AUTH_USER_MODEL

AUTH_USER_MODEL = 'user.User'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Session

SESSION_COOKIE_SAMESITE = "Strict"

# Rest Framework Configuration

REST_FRAMEWORK = REST_FRAMEWORK_AVAILABLE[ENVIRONMENT]

# CSRF

CSRF_USE_SESSIONS = False
CSRF_FAILURE_VIEW = "spa_security.views.csrf_error.csrf_error_view"

# CORS

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

# Sites

SITE_ID = 1

# URLS

LOGIN_URL = "/api/v1/auth/login/"
LOGIN_REDIRECT_URL = "/api/v1/auth/login/"
LOGOUT_REDIRECT_URL = None
ACCOUNT_LOGOUT_REDIRECT_URL = LOGIN_URL

# OAuth Parameters
GOOGLE_CALLBACK_URL = os.getenv("GOOGLE_CALLBACK_URL")

# API Versioning

DEFAULT_VERSION = "v1"
ALLOWED_VERSIONS = ("v1",)

# Watchman Settings

WATCHMAN_TOKENS = os.getenv("WATCHMAN_TOKENS", None)
WATCHMAN_CHECKS = ["watchman.checks.databases"]

# Pagination Settings

PAGE_SIZE = 50
PAGE_SIZE_MAX = 100
PAGE_SIZE_PARAM = "page_size"
PAGE_QUERY_PARAM = "page"

# Environment Specific Settings
ENVIRONMENT_SETTINGS = f"./environments/settings_{ENVIRONMENT}.py"
include(ENVIRONMENT_SETTINGS)
print(f"Loaded: {ENVIRONMENT_SETTINGS}")
