# Production Deployment for Panic
runtime: python38
entrypoint: gunicorn -k gevent -b :$PORT root.wsgi:application

default_expiration: "3d"
instance_class: F1
automatic_scaling:
  max_instances: 2
  min_instances: 1

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static/
  secure: always
  expiration: "3d"

- url: /.*
  script: auto
  secure: always

env_variables:
