# Generated by Django 3.0.12 on 2021-02-11 20:18

from django.db import migrations, models
import timezone_field.fields
import user.models.validators.user


class Migration(migrations.Migration):

  dependencies = [
      ('user', '0001_initial'),
  ]

  operations = [
      migrations.AddField(
          model_name='user',
          name='language_code',
          field=models.CharField(
              default='en',
              max_length=20,
              validators=[user.models.validators.user.validate_language]
          ),
      ),
      migrations.AddField(
          model_name='user',
          name='has_profile_initialized',
          field=models.BooleanField(default=False),
      ),
      migrations.AddField(
          model_name='user',
          name='timezone',
          field=timezone_field.fields.TimeZoneField(default='UTC'),
      ),
  ]
