# Generated by Django 3.2.3 on 2021-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('user', '0003_django_upgrade_20210319_1923'),
  ]

  operations = [
      migrations.AlterField(
          model_name='user',
          name='id',
          field=models.BigAutoField(
              auto_created=True,
              primary_key=True,
              serialize=False,
              verbose_name='ID'
          ),
      ),
  ]
