name: panic Automation

on:
  push:
  schedule:
    - cron:  '0 6 * * 1'
  workflow_dispatch:

jobs:

  push:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create Docker Mounted Content
      run: |
        echo | ssh-keygen
        touch ${HOME}/.gitconfig
        touch ${HOME}/.gitconfig_global
    - name: Ensure File System is Writable by the Container
      run: |
        sudo chmod -R o+w .
    - name: Build Container
      run: |
        docker-compose build
        docker-compose up -d
    - name: Run Toc Tree Checker
      run: |
        docker-compose exec -T panic bash -l -c 'scripts/commander.sh check-toctree'
    - name: Run Type Checker
      run: |
        docker-compose exec -T panic bash -l -c 'scripts/commander.sh types'
    - name: Run Sec Test
      run: |
        docker-compose exec -T panic bash -l -c 'scripts/commander.sh sectest'
    - name: Run Safety from the Host Machine
      run: |
        docker-compose exec -T panic bash -l -c 'pip freeze > safety.txt'
        sudo pip3 install wheel setuptools
        sudo pip3 install safety
        safety check -r safety.txt
    - name: Run Linter
      run: |
        docker-compose exec -T panic bash -l -c 'scripts/commander.sh lint'
    - name: Run Unit Tests
      run: |
        docker-compose exec -T panic bash -l -c 'scripts/commander.sh test coverage'
    - name: Run Integration Tests
      run: |
        docker-compose exec -T panic bash -l -c 'scripts/commander.sh test integration'
    - name: Report Job Status (Success)
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"panic backend build was successful!"}' "${WEBHOOK_URL}"
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    - name: Report Job Status
      if: failure() == true
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"panic backend build has failed!"}' "${WEBHOOK_URL}"
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    - name: Stage -- Deploy
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      run: |
        # Deploy to Stage
        echo -n "${ADMIN_ENV}" | base64 --decode > ./environments/admin.env
        echo -n "${STAGE_ENV}" | base64 --decode > ./environments/stage.env
        echo -n "${STAGE_SERVICE_ACCOUNT}" | base64 --decode > ./service-account.json
        docker-compose exec -T panic bash -l -c 'scripts/commander.sh deploy-stage'
      env:
        ADMIN_ENV: ${{ secrets.ADMIN_ENV }}
        STAGE_ENV: ${{ secrets.STAGE_ENV }}
        STAGE_SERVICE_ACCOUNT: ${{ secrets.STAGE_SERVICE_ACCOUNT }}
    - name: Stage -- Report Success
      if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"panic backend: automated deploy to stage!"}' "${WEBHOOK_URL}"
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    - name: Stage -- Report Failure
      if: failure() == true
      run: |
        [[ ${REF} == 'refs/heads/master' ]] && [[ ${EVENT} == 'push' ]] && curl -X POST -H 'Content-type: application/json' --data '{"text":"panic backend: stage deploy has failed!"}' "${WEBHOOK_URL}"
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        REF: ${{ github.ref }}
        EVENT: ${{ github.event_name }}

    - name: Production -- Detect A Release Tag
      if: contains(github.ref, '/tags/v') == true
      run: |
        GIT_DIFF=$(git diff origin/master)
        echo "GIT_DIFF=${GIT_DIFF}" >> $GITHUB_ENV
    - name: Production -- Ignore Non-Release Tags and Branches
      if: contains(github.ref, '/tags/v') != true
      run: |
        GIT_DIFF="not a release"
        echo "GIT_DIFF=${GIT_DIFF}" >> $GITHUB_ENV

    - name: Production -- Prepare Release Content
      if: env.GIT_DIFF == ''
      run: |
        NEWTAG=${GITHUB_REF#refs/tags/}
        echo "NEWTAG=${NEWTAG}" >> $GITHUB_ENV
        echo "{}" > package.json
    - name: Production -- Generate Changelog
      if: env.GIT_DIFF == ''
      uses: scottbrenner/generate-changelog-action@1.0.3
      id: Changelog
      env:
        REPO: ${{ github.repository }}
    - name: Production -- Create Release
      if: env.GIT_DIFF == ''
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEWTAG }}
        release_name: Release ${{ env.NEWTAG }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
          ## Deployment Checklist
          - [ ] Review Commit History
          - [ ] Ensure minimum frontend version is documented
          - [ ] Ensure readthedocs is building correctly
          - [ ] Ensure unnecessary alerts are ignored/disabled
          - [ ] Successful web/mobile tests completed in stage environment
          - [ ] Use Admin environment to complete database migrations
        draft: true
        prerelease: false
    - name: Production -- Report Success
      if: env.GIT_DIFF == ''
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"panic backend: automated release has been created for ${TAG}: https://github.com/niall-byrne/panic/releases\"}" "${WEBHOOK_URL}"
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        TAG: ${{ env.NEWTAG }}
    - name: Production -- Report Failure
      if: failure() == true && contains(github.ref, '/tags/v') == true
      run: |
        [[ -z ${GIT_DIFF} ]] && curl -X POST -H 'Content-type: application/json' --data '{"text":"panic backend: automated production release has failed!"}' "${WEBHOOK_URL}"
      env:
        WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GIT_DIFF: ${{ env.GIT_DIFF }}
