#!/bin/bash

set -eo pipefail

bypass() {

  # Bypass Unless GitHooks Are Enabled
  [[ "${GIT_HOOKS_PREPUSH}" != "1" ]] && exit 0

  remote_ref="${1}"
  protected_branches="${GIT_HOOKS_PROTECTED_HEADS}"

  if [[ ! ${remote_ref} =~ ${protected_branches} ]]; then
        exit 0
  fi

}

main() {

  IFS=' '
  while read local_ref local_sha remote_ref remote_sha; do

    bypass ${remote_ref}

    [[ ! -f /etc/container_release ]] && source environments/local.env

    bash scripts/commander.sh check-toctree
    bash scripts/commander.sh lint-diff
    bash scripts/commander.sh lint-extras
    bash scripts/commander.sh sectest
    bash scripts/commander.sh test-coverage
    bash scripts/commander.sh test-integration
    shellcheck -x scripts/*.sh
    shellcheck -x scripts/common/*.sh

  done

}

main
