#!/bin/bash

set -eo pipefail

bypass() {

  # Bypass Unless GitHooks Are Enabled
  [[ "${GIT_HOOKS_PRECOMMIT}" != "1" ]] && exit 0

  local_branch="$(git rev-parse --abbrev-ref HEAD)"
  protected_branches="${GIT_HOOKS_PROTECTED_BRANCHES}"

  if [[ ! ${local_branch} =~ ${protected_branches} ]]; then
        exit 0
  fi

}

main() {

  [[ ! -f /etc/container_release ]] && echo "Please make this commit inside the containerized environment." && exit 127

  bypass

  bash scripts/commander.sh check-toctree
  bash scripts/commander.sh lint-diff
  bash scripts/commander.sh lint-extras
  bash scripts/commander.sh sectest
  bash scripts/commander.sh test-coverage
  bash scripts/commander.sh test-integration

  if [[ -n "$(git diff)" ]]; then

    git status

    exec < /dev/tty
    echo -e "\\nWARNING: You have uncommitted changes!"
    read -r -p "Type 'yes' to confirm you wish to proceed with this commit: " confirm
    [[ ${confirm} != "yes" ]] && echo 'ABORTED' && exit 127

    exit 0

  fi

}

main
