#!/bin/bash

set -eo pipefail

bypass() {

  # Bypass Unless GitHooks Are Enabled
  [[ "${GIT_HOOKS_PREPUSH}" != "1" ]] && exit 0

  remote_ref="${1}"
  protected_branches="${GIT_HOOKS_PROTECTED_HEADS}"

  if [[ ! ${remote_ref} =~ ${protected_branches} ]]; then
        exit 0
  fi

}

main() {

  IFS=' '
  # shellcheck disable=SC2034
  while read -r local_ref local_sha remote_ref remote_sha; do

    [[ ! -f /etc/container_release ]] && echo "Please push this commit inside the containerized environment." && exit 127

    bypass "${remote_ref}"

    bash scripts/commander.sh check-toctree
    bash scripts/commander.sh lint
    bash scripts/commander.sh sectest
    bash scripts/commander.sh test-coverage
    bash scripts/commander.sh test-integration

  done

}

main
